services:
  node0:
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    networks:
      - rabbitmq-cluster
    hostname: node0
    container_name: rabbitmq0
    image: ${RABBITMQ_IMAGE:-rabbitmq:4.1}
    pull_policy: always
    ports:
      - "5672:5672"
      - "15672:15672"
    tty: true
    volumes:
      - ./configuration/:/etc/rabbitmq/
  node1:
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    networks:
      - rabbitmq-cluster
    hostname: node1
    container_name: rabbitmq1
    image: ${RABBITMQ_IMAGE:-rabbitmq:4.1}
    pull_policy: always
    ports:
      - "5673:5672"
      - "15673:15672"
    tty: true
    volumes:
      - ./configuration/:/etc/rabbitmq/
  node2:
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    networks:
      - rabbitmq-cluster
    hostname: node2
    container_name: rabbitmq2
    image: ${RABBITMQ_IMAGE:-rabbitmq:4.1}
    pull_policy: always
    ports:
      - "5674:5672"
      - "15674:15672"
    tty: true
    volumes:
      - ./configuration/:/etc/rabbitmq/
networks:
  rabbitmq-cluster:
