= RabbitMQ AMQP 1.0 Java Client
:revnumber: {project-version}
:revremark: ({build-number})
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/java]
:source-highlighter: prettify
:javadoc-url: https://rabbitmq.github.io/rabbitmq-amqp-java-client/snapshot/api

The RabbitMQ AMQP 1.0 Java Client is a library to communicate with RabbitMQ using https://www.rabbitmq.com/docs/amqp[AMQP 1.0].

It is **for RabbitMQ only**, it does not support other brokers.

== Pre-requisites

This library requires at least Java 11 (Java 21+ is recommended) and RabbitMQ 4.0 or more.

[[license]]
== License

The library is open source, developed https://github.com/rabbitmq/rabbitmq-amqp-java-client/[on GitHub], and is licensed under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache Public License 2.0]

== Dependencies

Use your favorite build management tool to add the client dependencies to your project.

=== Maven

.pom.xml
[source,xml,subs="attributes,specialcharacters"]
----
<dependencies>

  <dependency>
    <groupId>{project-group-id}</groupId>
    <artifactId>{project-artifact-id}</artifactId>
    <version>{project-version}</version>
  </dependency>

</dependencies>
----

Snapshots require to declare the <<snapshots,appropriate repository>>.

=== Gradle

.build.gradle
[source,groovy,subs="attributes,specialcharacters"]
----
dependencies {
  compile "{project-group-id}:{project-artifact-id}:{project-version}"
}
----

Snapshots require to declare the <<snapshots,appropriate repository>>.

[[snapshots]]
=== Snapshots

Releases are available from Maven Central, which does not require specific declaration.
Snapshots are available from a repository which must be declared in the dependency management configuration.

With Maven:

.Snapshot repository declaration for Maven
[source,xml,subs="attributes,specialcharacters"]
----
<repositories>

  <repository>
    <id>central-portal-snapshots</id>
    <url>https://central.sonatype.com/repository/maven-snapshots/</url>
    <snapshots><enabled>true</enabled></snapshots>
    <releases><enabled>false</enabled></releases>
  </repository>

</repositories>
----

With Gradle:

.Snapshot repository declaration for Gradle:
[source,groovy,subs="attributes,specialcharacters"]
----
repositories {
  maven {
    name = 'Central Portal Snapshots'
    url = 'https://central.sonatype.com/repository/maven-snapshots/'
    // Only search this repository for the specific dependency
    content {
      includeModule("{project-group-id}", "{project-artifact-id}")
    }
  }
  mavenCentral()
}
----

== Versioning

The RabbitMQ AMQP 1.0 Java Client is in development and stabilization phase.
When the stabilization phase ends, a 1.0.0 version will be cut, and
https://semver.org/[semantic versioning] is likely to be enforced.

Before reaching the stable phase, the client will use a versioning scheme of `[0.MINOR.PATCH]` where:

* `0` indicates the project is still in a stabilization phase.
* `MINOR` is a 0-based number incrementing with each new release cycle. It generally reflects significant changes like new features and potentially some programming interfaces changes.
* `PATCH` is a 0-based number incrementing with each service release, that is bux fixes.

Breaking changes between releases can happen but will be kept to a minimum.
The next section provides more details about the evolution of programming interfaces.

[[stability-of-programming-interfaces]]
== Stability of Programming Interfaces

The RabbitMQ AMQP 1.0 Java Client is in active development but its programming interfaces will remain as stable as possible. There is no guarantee though that they will remain completely stable, at least until it reaches version 1.0.0.

The client contains 2 sets of programming interfaces whose stability are of interest for application developers:

* Application Programming Interfaces (API): those are the ones used to write application logic.
They include the interfaces and classes in the `com.rabbitmq.client.amqp` package (e.g. `Connection`, `Publisher`, `Consumer`, `Message`).
These API constitute the main programming model of the client and will be kept as stable as possible.
* Service Provider Interfaces (SPI): those are interfaces to implement mainly technical behavior in the client.
They are not meant to be used to implement application logic.
Application developers may have to refer to them in the configuration phase and if they want to customize some internal behavior of the client.
SPI packages and interfaces are marked as such in their Javadoc.
_These SPI are susceptible to change, but this should have no impact on most applications_, as the changes are likely to be limited to the client internals.

include::usage.adoc[]

include::appendixes.adoc[]
