:test-examples: ../../test/java/com/rabbitmq/model/docs

[[api-overview]]
== API Overview

=== Environment

The `Environment` is the entry point for applications.
It exposes an API to create connections.

.Environment creation
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=environment-creation]
--------

=== Connection

The `Connection` represents an AMQP 1.0 connection on top of TCP.
It exposes an API to create publishers, consumers, and to manage resources (exchanges, queues, and bindings).

.Connection creation
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=connection-creation]
--------


=== Publishing

.Publisher creation
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=publisher-creation]
--------

.Message creation
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=message-creation]
--------

.Message publishing
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=message-publishing]
--------

.Target address format: exchange and key
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=target-address-exchange-key]
--------
<1> Translates to `/exchange/foo/key/bar`

.Target address format: exchange
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=target-address-exchange]
--------
<1> Translates to `/exchange/foo`

.Target address format: queue
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=target-address-queue]
--------
<1> Translates to `/queue/some-queue`

.Target address format: address in `to` field
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=target-address-null]
--------
<1> No address specified, translates to `null`
<2> Exchange and key in message `to` field
<3> Exchange in message `to` field

=== Consuming

.Consuming from a queue
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=consumer]
--------
<1> Process the message
<2> Accept (acknowledge) the message

=== Resource Management

The `Management` object is the entry point to deal with resources.
It is accessible from the `Environment`.

.Getting the management object from the environment
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=management]
--------

==== Exchanges

.Exchange creation (built-in type)
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=fanout-exchange]
--------

.Exchange creation (not built-in)
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=delayed-message-exchange]
--------

.Exchange deletion
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=delete-exchange]
--------

==== Queues

.Queue creation
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=queue-creation]
--------

There is no need to remember the argument names and types thanks to explicit configuration methods:

.Queue creation with arguments
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=queue-creation-with-arguments]
--------
<1> Explicit methods for common queue arguments

.Quorum queue creation
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=quorum-queue-creation]
--------
<1> Queue-type-specific configuration helper

.Queue deletion
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=queue-deletion]
--------

==== Bindings

.Exchange-to-queue binding
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=binding]
--------

.Exchange-to-exchange binding
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=exchange-binding]
--------

.Unbinding
[source,java,indent=0]
--------
include::{test-examples}/Api.java[tag=unbinding]
--------

== Dependencies

Use your favorite build management tool to add the client dependencies to your project.

=== Maven

.pom.xml
[source,xml,subs="attributes,specialcharacters"]
----
<dependencies>

  <dependency>
    <groupId>com.rabbitmq.amqp</groupId>
    <artifactId>{project-artifact-id}</artifactId>
    <version>{project-version}</version>
  </dependency>

</dependencies>
----

Snapshots require to declare the <<snapshots,appropriate repository>>.

=== Gradle

.build.gradle
[source,groovy,subs="attributes,specialcharacters"]
----
dependencies {
  compile "com.rabbitmq.amqp:{project-artifact-id}:{project-version}"
}
----

Snapshots require to declare the <<snapshots,appropriate repository>>.

[[snapshots]]
=== Snapshots

Releases are available from Maven Central, which does not require specific declaration.
Snapshots are available from a repository which must be declared in the dependency management configuration.

With Maven:

.Snapshot repository declaration for Maven
[source,xml,subs="attributes,specialcharacters"]
----
<repositories>

  <repository>
    <id>ossrh</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <snapshots><enabled>true</enabled></snapshots>
    <releases><enabled>false</enabled></releases>
  </repository>

</repositories>
----

With Gradle:

.Snapshot repository declaration for Gradle:
[source,groovy,subs="attributes,specialcharacters"]
----
repositories {
  maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
  mavenCentral()
}
----

