name: Test against supported Java versions

on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        distribution: [ 'temurin' ]
        version: [ '11', '17', '21', '22-ea' ]
        include:
          - distribution: 'semeru'
            version: '17'
    name:  Test against Java ${{ matrix.distribution }} ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Checkout ProtonJ2
        uses: actions/checkout@v4
        with:
          repository: apache/qpid-protonj2
          path: './qpid-protonj2'
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.version }}
          cache: 'maven'
      - name: Start broker
        run: ci/start-broker.sh
        env:
          RABBITMQ_IMAGE: 'pivotalrabbitmq/rabbitmq:amqp-management-otp-max-bazel'
      - name: Display Java version
        run: ./mvnw --version
      - name: Install ProtonJ2
        run: |
          mvn --file qpid-protonj2 clean install -Dmaven.test.skip
      - name: Test
        run: |
          ./mvnw verify -Drabbitmqctl.bin=DOCKER:rabbitmq \
            -Dnet.bytebuddy.experimental=true
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq